<!DOCTYPE ships[
        <!ELEMENT ships (ship)>
        <!ELEMENT ship (speed, health, asset, weaponslot)>
        <!ATTLIST ship Name CDATA #IMPLIED>
        <!ELEMENT speed (#PCDATA)>
        <!ELEMENT health (#PCDATA)>
        <!ELEMENT asset (#PCDATA)>
        <!ELEMENT weaponslot (position,weapon)>
        <!ELEMENT position EMPTY>
        <!ATTLIST position x CDATA #IMPLIED>
        <!ATTLIST position y CDATA #IMPLIED>
        <!ELEMENT weapon (weapontype,mirrorhoriz)>
        <!ATTLIST weapon Name CDATA #IMPLIED>
        <!ELEMENT weapontype EMPTY>
        <!ATTLIST weapontype Name CDATA #IMPLIED>
        <!ELEMENT mirrorhoriz EMPTY>
        <!ATTLIST mirrorhoriz Mirror CDATA #IMPLIED>
        ]>

<ships>
    <ship Name="Player01">
        <speed>1.2</speed>
        <health>20</health>
        <asset>playerShip1_blue</asset>
        <weaponslot>
            <position x="5" y="5"/>
            <weapon Name="Laser1">
                <weapontype Name="Laser"/>
                <mirrorhoriz Mirror="true"/>
            </weapon>
        </weaponslot>
    </ship>
    <ship Name="Enemy01">
        <speed>1.2</speed>
        <health>10</health>
        <asset>Enemies/enemyRed1</asset>
        <weaponslot>
            <position x="3" y="3"/>
            <weapon Name="Laser1">
                <weapontype Name="Laser"/>
                <mirrorhoriz Mirror="true"/>
            </weapon>
        </weaponslot>
    </ship>
</ships>